package com.bwensun.generator.domain;

import java.io.Serializable;
import java.util.Date;
import lombok.Getter;
import lombok.Setter;
import lombok.ToString;

/**
 * 经销主信息表
 *
 * @author 郑建雄
 * @date 2022/02/22
 */
@Getter
@Setter
@ToString
public class BwDistributionMain implements Serializable {
    /**
     * ID
     */
    private Short id;

    /**
     * 供应商税号
     */
    private Object supplierTaxno;

    /**
     * 供应商名称
     */
    private Object supplierName;

    /**
     * 供应商编码
     */
    private Object supplierCode;

    /**
     * 品牌
     */
    private Object brand;

    /**
     * 合同有效期开始
     */
    private Date contractDateFrom;

    /**
     * 合同有效期结束
     */
    private Date contractDateTo;

    /**
     * 结算状态
     */
    private Object state;

    /**
     * 订单编号
     */
    private Object orderNo;

    /**
     * 来源系统
     */
    private Object sourceSystem;

    /**
     * 不含税金额
     */
    private Short amount;

    /**
     * 价税合计
     */
    private Short totalAmount;

    /**
     * 税额
     */
    private Short taxAmount;

    /**
     * 购方编码
     */
    private Object buyCode;

    /**
     * 购方名称
     */
    private Object buyName;

    /**
     * 购方机构id
     */
    private Short orgId;

    /**
     * 购方税号
     */
    private Object buyTaxno;

    /**
     * 创建日期
     */
    private Date creatDate;

    /**
     * 修改日期
     */
    private Date updateDate;

    /**
     * 修改人
     */
    private Object updateName;

    /**
     * 修改人id
     */
    private Short updateUserId;

    /**
     * 备注
     */
    private Object remarks;

    /**
     * 结算单号
     */
    private Object settlementNo;

    /**
     * 销方机构id
     */
    private Short supplierOrgId;

    /**
     * 门店名称
     */
    private String buyerStoreName;

    /**
     * 交货单编号
     */
    private String deliveryNo;

    /**
     * 结算方式 1-现金结算
     */
    private String settlementType;

    /**
     * 签收状态（0未签收，1已签收，2已退回,默认0）
     */
    private Object receivedStatus;

    /**
     * 退回原因
     */
    private Object returnMsg;

    /**
     * 结算日期
     */
    private Date settlementTime;

    /**
     * 销方门店名称
     */
    private Object supplierStoreName;

    /**
     * 店铺
     */
    private Object store;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table BW_DISTRIBUTION_MAIN
     *
     * @mbg.generated Tue Feb 22 10:57:45 CST 2022
     */
    private static final long serialVersionUID = 1L;
}